### ISSUE TITLE
[Bug] Cast button not available

### ISSUE THREAD

**Issue by maciak** [cuynu/ytvanced#109]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version: 18.01.38
Vanced MicroG: [0.2.26.225014](https://github.com/cuynu/ytvanced/releases/download/18.02.33/Vanced.microG.0.2.26.225014.apk)
Device: Redmi Note 10 Pro

Description
===========
Cast button not available. Not sure if why but the ICon just does not show up on any video. My wife on her Samsung a53 has exact same issue.

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Go to Vanced settings -> Layout and disable "Hide cast button" toggle.
 Due to microG Chromecast issue, if your TV use Chromecast v2 (Android TVs) so you will can't cast by select device from cast, instead, can only be cast through the TV code. Chromecast v1 devices (Smart TV LED eg: Samsung,LG,etc) can cast normally without TV Code like Android TV

**Comment by maciak** [comment]
That worked a treat. Thanks! :)
