### ISSUE TITLE
Not Closing App

### ISSUE THREAD

**Issue by alpha-alexxx** [cuynu/ytvanced#13]
From 2 or 3 days i am facing new problem. When i press Back button to close the app, it should be closed by it, but the Back button is not working in app and app is not Closing by pressing back button. Please look into this issue. Maybe many people are facing this issue.
@cuynu

**Comment by cuynu** [comment]
What your version are you using?

**Comment by alpha-alexxx** [comment]
Letest version

**Comment by cuynu** [comment]
> Letest version

Try disable Return YouTube Dislikes on YouTube settings

**Comment by cuynu** [comment]
I still can quit the app by pressing back button, try clear app data and try again

**Comment by UsmanAhmadSaeed** [comment]
Hi @cuynu 

First, I appreciate the work you've put here to continue the Vanced legacy.

Secondly, I'm facing the same issue, along with "swipe down to refresh" not working.
Clearing app data solves the issue for a while, but it re-appears when I change any settings. I've tried with different settings to see if any one causes the problem, but the issue is persistent regardless of setting changed. 
For example, I turned off bed-time and break reminders in general settings and app quit on back button, as well as swipe down refresh stopped working.
I'm using the latest version of Vanced (17.33.42) and microG (0.2.25.223212) on a Samsung Galaxy, Android 12, One UI 4.1, if that helps.
Hope this gives more info to recreate the issue and bug fix.

Appreciate the work again. Thanks!

**Comment by alpha-alexxx** [comment]
> I still can quit the app by pressing the back button, try clear app data and try again

Hey, I tried clearing cache and clearing data, but there is not any solution. Now on both phones, the bug is raised by it. Previously there was only problem with the Redmi phone, but now in my Realme Phone.

**Comment by cuynu** [comment]
> > I still can quit the app by pressing the back button, try clear app data and try again
> 
> Hey, I tried clearing cache and clearing data, but there is not any solution. Now on both phones, the bug is raised by it. Previously there was only problem with the Redmi phone, but now in my Realme Phone.

Ans: This is one of the things Google is testing.
Google has built a pull-down refresh feature and a back-key feature inside the ad layout from YouTube's home feed.

In other words, in the latest version of YouTube, if you block the layout ads from the home feed, it means that the pull-down refresh function and the back-key function will not be available (because those functions are included in the layout ads)

Turn off the 'Settings > Vanced Settings > Ad settings > General layout ad removal' toggle

Ads will appear in YouTube Vanced home feed, but pull-down refresh and back-key functionality will work in the home feed.

This is an issue that no one has been able to fix since [YouTube Vanced Official v15.43.32](https://github.com/TeamVanced/Vanced/issues/252). This is an issue that no one can easily solve.

**Comment by alpha-alexxx** [comment]
Thanks brother now it is working fine.

**Comment by winte1** [comment]
In fact, it can be solved, as long as the original data is loaded every time it is started, but some new functions may not be available

**Comment by cuynu** [comment]
> In fact, it can be solved, as long as the original data is loaded every time it is started, but some new functions may not be available

No, the features you mentioned above still work
