### ISSUE TITLE
[Bug] Package analysis failed during installation

### ISSUE THREAD

**Issue by MaxenceLearn** [cuynu/ytvanced#180]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 7.0
YouTube Vanced Version: 18.02.33
Vanced MicroG: Vanced.microG.0.2.26.225014
Device: 

Description
===========
Package analysis failed when trying to install YTB vanced 

Steps to reproduce
==================
No step just trying to install vanced on a android 7.0

Expected result
===============

Actual result
=============
Package analysis failed

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Use 17.34.36 for Android 6 & 7 because YouTube has dropped support for Android 6 & 7 since 17.35.xx, so the last version support for Android 6 & 7 is 17.34.xx, there is no way to install 17.35.xx and above on Android 6 & 7 because the base only support Android 8+

https://github.com/cuynu/ytvanced/wiki/17.34.36-(Android-6-and-7)
