### ISSUE TITLE
arm v8 version 

### ISSUE THREAD

**Issue by rajarshikhatua100** [cuynu/ytvanced#21]
please provide arm v8 version

**Comment by cuynu** [comment]
My YouTube Vanced builds are have Universal architecture : (arm64-v8a,armeabi-v7a,x86,x86_64)

**Comment by cuynu** [comment]
All architecture are in one apk file

**Comment by rajarshikhatua100** [comment]
can you provide only arm68-v8a apk, the universal apk is heav6

**Comment by cuynu** [comment]
I only want provide universal architecture version, this is last version that i provide only arm64-v8a architecture because i was so tired with this

https://github.com/cuynu/ytvanced/releases/download/17.41.34/YouTube.Vanced.v17.41.34_Black_arm64_v8a.apk

https://github.com/cuynu/ytvanced/releases/download/17.41.34/YouTube.Vanced.v17.41.34_Dark_arm64_v8a.apk

**Comment by rajarshikhatua100** [comment]
please do it for us, this will be so much helpful for us

**Comment by rajarshikhatua100** [comment]
Thanks

**Comment by cuynu** [comment]
Okay, and please note do not ask me or request anything by create issues, go to Discussion tab instead.
