### ISSUE TITLE
Swipe to refresh sometimes not working 

### ISSUE THREAD

**Issue by Mehedi5585** [cuynu/ytvanced#53]
Swiped to refresh sometimes not working

 - Device: [e.g. Android device]
 - OS: [e.g. Android 12

**Comment by cuynu** [comment]
In the latest version of YouTube, if you block the layout ads from the home feed, it means that the pull-down refresh function and the back-key function will not be available (because those functions are included in the layout ads)

Turn off the 'Settings > Vanced Settings > Ad settings > General layout ad removal' toggle

Ads will appear in YouTube Vanced home feed, but pull-down refresh and back-key functionality will work in the home feed.
