### ISSUE TITLE
YouTube vanced not is not closed by using back button

### ISSUE THREAD

**Issue by spidy2356** [cuynu/ytvanced#55]
PLEASE FILL OUT THIS FORM, DO NOT CREATE AN ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE. 

**Describe the bug**
YouTube vanced not closed after using back button, most of the time 
**To Reproduce**

**Expected behavior**

**Screenshot/Videos**
If applicable, upload screenshot or videos to help explain your problem.

https://user-images.githubusercontent.com/101243689/202987267-e951d144-2489-407d-aea7-0809d02a6160.mp4

 - Device: [e.g. Android device] Poco x2
 - OS: [e.g. Android 11] android 11
 - YouTube Vanced Version [e.g. 17.03.38] 17.45.34
- Vanced MicroG version [e.g. 20220230] 0.2.24.220220

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
In the latest version of YouTube, if you block the layout ads from the home feed, it means that the pull-down refresh function and the back-key function will not be available (because those functions are included in the layout ads)

Turn off the 'Settings > Vanced Settings > Ad settings > General layout ad removal' toggle

Ads will appear in YouTube Vanced home feed, but pull-down refresh and back-key functionality will work in the home feed.

This is an issue that no one has been able to fix since YouTube Vanced Official v15.43.32. This is an issue that no one can easily solve.

**Comment by spidy2356** [comment]
Ok. I understand now. Thank you for your fast response
